# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gnss/signa_onboard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gnss/signa_onboard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gnss/signa_onboard/CMakeFiles /home/gnss/signa_onboard/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gnss/signa_onboard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named signa

# Build rule for target.
signa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 signa
.PHONY : signa

# fast build rule for target.
signa/fast:
	$(MAKE) -f CMakeFiles/signa.dir/build.make CMakeFiles/signa.dir/build
.PHONY : signa/fast

#=============================================================================
# Target rules for targets named novatel

# Build rule for target.
novatel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 novatel
.PHONY : novatel

# fast build rule for target.
novatel/fast:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/build
.PHONY : novatel/fast

src/matops.o: src/matops.c.o

.PHONY : src/matops.o

# target to build an object file
src/matops.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/matops.c.o
.PHONY : src/matops.c.o

src/matops.i: src/matops.c.i

.PHONY : src/matops.i

# target to preprocess a source file
src/matops.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/matops.c.i
.PHONY : src/matops.c.i

src/matops.s: src/matops.c.s

.PHONY : src/matops.s

# target to generate assembly for a file
src/matops.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/matops.c.s
.PHONY : src/matops.c.s

src/mavlink/mavlink_main.o: src/mavlink/mavlink_main.c.o

.PHONY : src/mavlink/mavlink_main.o

# target to build an object file
src/mavlink/mavlink_main.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/mavlink/mavlink_main.c.o
.PHONY : src/mavlink/mavlink_main.c.o

src/mavlink/mavlink_main.i: src/mavlink/mavlink_main.c.i

.PHONY : src/mavlink/mavlink_main.i

# target to preprocess a source file
src/mavlink/mavlink_main.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/mavlink/mavlink_main.c.i
.PHONY : src/mavlink/mavlink_main.c.i

src/mavlink/mavlink_main.s: src/mavlink/mavlink_main.c.s

.PHONY : src/mavlink/mavlink_main.s

# target to generate assembly for a file
src/mavlink/mavlink_main.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/mavlink/mavlink_main.c.s
.PHONY : src/mavlink/mavlink_main.c.s

src/mavlink/tmtc_ladgnss.o: src/mavlink/tmtc_ladgnss.c.o

.PHONY : src/mavlink/tmtc_ladgnss.o

# target to build an object file
src/mavlink/tmtc_ladgnss.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/mavlink/tmtc_ladgnss.c.o
.PHONY : src/mavlink/tmtc_ladgnss.c.o

src/mavlink/tmtc_ladgnss.i: src/mavlink/tmtc_ladgnss.c.i

.PHONY : src/mavlink/tmtc_ladgnss.i

# target to preprocess a source file
src/mavlink/tmtc_ladgnss.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/mavlink/tmtc_ladgnss.c.i
.PHONY : src/mavlink/tmtc_ladgnss.c.i

src/mavlink/tmtc_ladgnss.s: src/mavlink/tmtc_ladgnss.c.s

.PHONY : src/mavlink/tmtc_ladgnss.s

# target to generate assembly for a file
src/mavlink/tmtc_ladgnss.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/mavlink/tmtc_ladgnss.c.s
.PHONY : src/mavlink/tmtc_ladgnss.c.s

src/nmea/context.o: src/nmea/context.c.o

.PHONY : src/nmea/context.o

# target to build an object file
src/nmea/context.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/context.c.o
.PHONY : src/nmea/context.c.o

src/nmea/context.i: src/nmea/context.c.i

.PHONY : src/nmea/context.i

# target to preprocess a source file
src/nmea/context.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/context.c.i
.PHONY : src/nmea/context.c.i

src/nmea/context.s: src/nmea/context.c.s

.PHONY : src/nmea/context.s

# target to generate assembly for a file
src/nmea/context.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/context.c.s
.PHONY : src/nmea/context.c.s

src/nmea/generate.o: src/nmea/generate.c.o

.PHONY : src/nmea/generate.o

# target to build an object file
src/nmea/generate.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/generate.c.o
.PHONY : src/nmea/generate.c.o

src/nmea/generate.i: src/nmea/generate.c.i

.PHONY : src/nmea/generate.i

# target to preprocess a source file
src/nmea/generate.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/generate.c.i
.PHONY : src/nmea/generate.c.i

src/nmea/generate.s: src/nmea/generate.c.s

.PHONY : src/nmea/generate.s

# target to generate assembly for a file
src/nmea/generate.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/generate.c.s
.PHONY : src/nmea/generate.c.s

src/nmea/generator.o: src/nmea/generator.c.o

.PHONY : src/nmea/generator.o

# target to build an object file
src/nmea/generator.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/generator.c.o
.PHONY : src/nmea/generator.c.o

src/nmea/generator.i: src/nmea/generator.c.i

.PHONY : src/nmea/generator.i

# target to preprocess a source file
src/nmea/generator.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/generator.c.i
.PHONY : src/nmea/generator.c.i

src/nmea/generator.s: src/nmea/generator.c.s

.PHONY : src/nmea/generator.s

# target to generate assembly for a file
src/nmea/generator.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/generator.c.s
.PHONY : src/nmea/generator.c.s

src/nmea/gmath.o: src/nmea/gmath.c.o

.PHONY : src/nmea/gmath.o

# target to build an object file
src/nmea/gmath.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/gmath.c.o
.PHONY : src/nmea/gmath.c.o

src/nmea/gmath.i: src/nmea/gmath.c.i

.PHONY : src/nmea/gmath.i

# target to preprocess a source file
src/nmea/gmath.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/gmath.c.i
.PHONY : src/nmea/gmath.c.i

src/nmea/gmath.s: src/nmea/gmath.c.s

.PHONY : src/nmea/gmath.s

# target to generate assembly for a file
src/nmea/gmath.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/gmath.c.s
.PHONY : src/nmea/gmath.c.s

src/nmea/info.o: src/nmea/info.c.o

.PHONY : src/nmea/info.o

# target to build an object file
src/nmea/info.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/info.c.o
.PHONY : src/nmea/info.c.o

src/nmea/info.i: src/nmea/info.c.i

.PHONY : src/nmea/info.i

# target to preprocess a source file
src/nmea/info.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/info.c.i
.PHONY : src/nmea/info.c.i

src/nmea/info.s: src/nmea/info.c.s

.PHONY : src/nmea/info.s

# target to generate assembly for a file
src/nmea/info.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/info.c.s
.PHONY : src/nmea/info.c.s

src/nmea/parse.o: src/nmea/parse.c.o

.PHONY : src/nmea/parse.o

# target to build an object file
src/nmea/parse.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/parse.c.o
.PHONY : src/nmea/parse.c.o

src/nmea/parse.i: src/nmea/parse.c.i

.PHONY : src/nmea/parse.i

# target to preprocess a source file
src/nmea/parse.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/parse.c.i
.PHONY : src/nmea/parse.c.i

src/nmea/parse.s: src/nmea/parse.c.s

.PHONY : src/nmea/parse.s

# target to generate assembly for a file
src/nmea/parse.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/parse.c.s
.PHONY : src/nmea/parse.c.s

src/nmea/parser.o: src/nmea/parser.c.o

.PHONY : src/nmea/parser.o

# target to build an object file
src/nmea/parser.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/parser.c.o
.PHONY : src/nmea/parser.c.o

src/nmea/parser.i: src/nmea/parser.c.i

.PHONY : src/nmea/parser.i

# target to preprocess a source file
src/nmea/parser.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/parser.c.i
.PHONY : src/nmea/parser.c.i

src/nmea/parser.s: src/nmea/parser.c.s

.PHONY : src/nmea/parser.s

# target to generate assembly for a file
src/nmea/parser.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/parser.c.s
.PHONY : src/nmea/parser.c.s

src/nmea/sentence.o: src/nmea/sentence.c.o

.PHONY : src/nmea/sentence.o

# target to build an object file
src/nmea/sentence.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/sentence.c.o
.PHONY : src/nmea/sentence.c.o

src/nmea/sentence.i: src/nmea/sentence.c.i

.PHONY : src/nmea/sentence.i

# target to preprocess a source file
src/nmea/sentence.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/sentence.c.i
.PHONY : src/nmea/sentence.c.i

src/nmea/sentence.s: src/nmea/sentence.c.s

.PHONY : src/nmea/sentence.s

# target to generate assembly for a file
src/nmea/sentence.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/sentence.c.s
.PHONY : src/nmea/sentence.c.s

src/nmea/time.o: src/nmea/time.c.o

.PHONY : src/nmea/time.o

# target to build an object file
src/nmea/time.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/time.c.o
.PHONY : src/nmea/time.c.o

src/nmea/time.i: src/nmea/time.c.i

.PHONY : src/nmea/time.i

# target to preprocess a source file
src/nmea/time.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/time.c.i
.PHONY : src/nmea/time.c.i

src/nmea/time.s: src/nmea/time.c.s

.PHONY : src/nmea/time.s

# target to generate assembly for a file
src/nmea/time.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/time.c.s
.PHONY : src/nmea/time.c.s

src/nmea/tok.o: src/nmea/tok.c.o

.PHONY : src/nmea/tok.o

# target to build an object file
src/nmea/tok.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/tok.c.o
.PHONY : src/nmea/tok.c.o

src/nmea/tok.i: src/nmea/tok.c.i

.PHONY : src/nmea/tok.i

# target to preprocess a source file
src/nmea/tok.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/tok.c.i
.PHONY : src/nmea/tok.c.i

src/nmea/tok.s: src/nmea/tok.c.s

.PHONY : src/nmea/tok.s

# target to generate assembly for a file
src/nmea/tok.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/nmea/tok.c.s
.PHONY : src/nmea/tok.c.s

src/novatel.o: src/novatel.cpp.o

.PHONY : src/novatel.o

# target to build an object file
src/novatel.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/novatel.cpp.o
.PHONY : src/novatel.cpp.o

src/novatel.i: src/novatel.cpp.i

.PHONY : src/novatel.i

# target to preprocess a source file
src/novatel.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/novatel.cpp.i
.PHONY : src/novatel.cpp.i

src/novatel.s: src/novatel.cpp.s

.PHONY : src/novatel.s

# target to generate assembly for a file
src/novatel.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/novatel.cpp.s
.PHONY : src/novatel.cpp.s

src/signa_core.o: src/signa_core.c.o

.PHONY : src/signa_core.o

# target to build an object file
src/signa_core.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_core.c.o
.PHONY : src/signa_core.c.o

src/signa_core.i: src/signa_core.c.i

.PHONY : src/signa_core.i

# target to preprocess a source file
src/signa_core.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_core.c.i
.PHONY : src/signa_core.c.i

src/signa_core.s: src/signa_core.c.s

.PHONY : src/signa_core.s

# target to generate assembly for a file
src/signa_core.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_core.c.s
.PHONY : src/signa_core.c.s

src/signa_main.o: src/signa_main.cpp.o

.PHONY : src/signa_main.o

# target to build an object file
src/signa_main.cpp.o:
	$(MAKE) -f CMakeFiles/signa.dir/build.make CMakeFiles/signa.dir/src/signa_main.cpp.o
.PHONY : src/signa_main.cpp.o

src/signa_main.i: src/signa_main.cpp.i

.PHONY : src/signa_main.i

# target to preprocess a source file
src/signa_main.cpp.i:
	$(MAKE) -f CMakeFiles/signa.dir/build.make CMakeFiles/signa.dir/src/signa_main.cpp.i
.PHONY : src/signa_main.cpp.i

src/signa_main.s: src/signa_main.cpp.s

.PHONY : src/signa_main.s

# target to generate assembly for a file
src/signa_main.cpp.s:
	$(MAKE) -f CMakeFiles/signa.dir/build.make CMakeFiles/signa.dir/src/signa_main.cpp.s
.PHONY : src/signa_main.cpp.s

src/signa_monitor.o: src/signa_monitor.c.o

.PHONY : src/signa_monitor.o

# target to build an object file
src/signa_monitor.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_monitor.c.o
.PHONY : src/signa_monitor.c.o

src/signa_monitor.i: src/signa_monitor.c.i

.PHONY : src/signa_monitor.i

# target to preprocess a source file
src/signa_monitor.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_monitor.c.i
.PHONY : src/signa_monitor.c.i

src/signa_monitor.s: src/signa_monitor.c.s

.PHONY : src/signa_monitor.s

# target to generate assembly for a file
src/signa_monitor.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_monitor.c.s
.PHONY : src/signa_monitor.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... signa"
	@echo "... novatel"
	@echo "... src/matops.o"
	@echo "... src/matops.i"
	@echo "... src/matops.s"
	@echo "... src/mavlink/mavlink_main.o"
	@echo "... src/mavlink/mavlink_main.i"
	@echo "... src/mavlink/mavlink_main.s"
	@echo "... src/mavlink/tmtc_ladgnss.o"
	@echo "... src/mavlink/tmtc_ladgnss.i"
	@echo "... src/mavlink/tmtc_ladgnss.s"
	@echo "... src/nmea/context.o"
	@echo "... src/nmea/context.i"
	@echo "... src/nmea/context.s"
	@echo "... src/nmea/generate.o"
	@echo "... src/nmea/generate.i"
	@echo "... src/nmea/generate.s"
	@echo "... src/nmea/generator.o"
	@echo "... src/nmea/generator.i"
	@echo "... src/nmea/generator.s"
	@echo "... src/nmea/gmath.o"
	@echo "... src/nmea/gmath.i"
	@echo "... src/nmea/gmath.s"
	@echo "... src/nmea/info.o"
	@echo "... src/nmea/info.i"
	@echo "... src/nmea/info.s"
	@echo "... src/nmea/parse.o"
	@echo "... src/nmea/parse.i"
	@echo "... src/nmea/parse.s"
	@echo "... src/nmea/parser.o"
	@echo "... src/nmea/parser.i"
	@echo "... src/nmea/parser.s"
	@echo "... src/nmea/sentence.o"
	@echo "... src/nmea/sentence.i"
	@echo "... src/nmea/sentence.s"
	@echo "... src/nmea/time.o"
	@echo "... src/nmea/time.i"
	@echo "... src/nmea/time.s"
	@echo "... src/nmea/tok.o"
	@echo "... src/nmea/tok.i"
	@echo "... src/nmea/tok.s"
	@echo "... src/novatel.o"
	@echo "... src/novatel.i"
	@echo "... src/novatel.s"
	@echo "... src/signa_core.o"
	@echo "... src/signa_core.i"
	@echo "... src/signa_core.s"
	@echo "... src/signa_main.o"
	@echo "... src/signa_main.i"
	@echo "... src/signa_main.s"
	@echo "... src/signa_monitor.o"
	@echo "... src/signa_monitor.i"
	@echo "... src/signa_monitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

